// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package controllerLogic;

/************************************************************/
/**
 * 
 * Generated from Papyrus
 * class Course {
  * 
  * 	private stream_id: Integer;
  * 	private course_id: Integer;
  * 	public course_name: String;
  * 	public selectCourse(in straem_id: Integer, in course_id: Integer);
  * 	public addCourse(in stream_id: Integer, in course_id: Integer,
  * 		in course_name: String): Boolean;
  * 	public updateCourse(in course_id: Integer, in course_name: String): Boolean;
  * 	public deleteCourse(in course_id: Integer): Boolean;
  * 	public getCourse_id(): Integer;
  * 	public setCourse_id();
  * 
  * }
 */
public class Course {
	/**
	 * 
	 */
	private int stream_id;
	/**
	 * 
	 */
	private int course_id;
	/**
	 * 
	 */
	public String course_name;

	/**
	 * 
	 * @param straem_id 
	 * @param course_id 
	 */
	public void selectCourse(int straem_id, int course_id) {
	}

	/**
	 * 
	 * @param stream_id 
	 * @param course_id 
	 * @param course_name 
	 * @return 
	 */
	public boolean addCourse(int stream_id, int course_id, String course_name) {
		return true;
	}

	/**
	 * 
	 * @param course_id 
	 * @param course_name 
	 * @return 
	 */
	public boolean updateCourse(int course_id, String course_name) {
		return true;
	}

	/**
	 * 
	 * @param course_id 
	 * @return 
	 */
	public boolean deleteCourse(int course_id) {
		return true;
		
	}

	/**
	 * 
	 * @return 
	 */
	public int getCourse_id() {
		return course_id;
	}

	/**
	 * 
	 * @param course_id 
	 */
	public void setCourse_id(int course_id) {
	}
};
