// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package controllerLogic;

/************************************************************/
/**
 * class Deliverable {
  * 
  * 	private deliverable_id: Integer;
  * 	public doc_type: String;
  * 	public doc_name: String;
  * 	public addDeliverable(in deliverable_id: Integer, in doc_type: String,
  * 		in doc_name: String): Boolean;
  * 	public updateDeliverable(in deliverable_id: Integer, in doc_type: String,
  * 		in doc_name: String): Boolean;
  * 	public removeDeliverable(in deliverable_id: Integer): Boolean;
  * 	public getDeliverable_id(): Integer;
  * 	public setDeliverable_id(in deliverable_id: Integer);
  * 
  * }
 */
public class Deliverable {
	/**
	 * 
	 */
	private int deliverable_id;
	/**
	 * 
	 */
	public String doc_type;
	/**
	 * 
	 */
	public String doc_name;

	/**
	 * 
	 * @param deliverable_id 
	 * @param doc_type 
	 * @param doc_name 
	 * @return 
	 */
	public boolean addDeliverable(int deliverable_id, String doc_type, String doc_name) {
		return true;
	}

	/**
	 * 
	 * @param deliverable_id 
	 * @param doc_type 
	 * @param doc_name 
	 * @return 
	 */
	public boolean updateDeliverable(int deliverable_id, String doc_type, String doc_name) {
		return true;
	}

	/**
	 * 
	 * @param deliverable_id 
	 * @return 
	 */
	public boolean removeDeliverable(int deliverable_id) {
		return true;
	}

	/**
	 * 
	 * @return 
	 */
	public int getDeliverable_id() {
		return deliverable_id;
	}

	/**
	 * 
	 * @param deliverable_id 
	 */
	public void setDeliverable_id(int deliverable_id) {
	}
};
