// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package controllerLogic;

import controllerLogic.Course;
import controllerLogic.Deliverable;

/************************************************************/
/**
 * class Grade {
  * 
  * 	public grade_type: String;
  * 	private student_id: Integer;
  * 	public course: Course;
  * 	public deliverable: Deliverable;
  * 	public viewGrades(in student_id: Integer): EEList;
  * 	public updateGrades(in student_id: Integer, in grade_type: String): Boolean;
  * 
  * }
 */
public class Grade {
	/**
	 * 
	 */
	public String grade_type;
	/**
	 * 
	 */
	private int student_id;
	/**
	 * 
	 */
	public Course course;
	/**
	 * 
	 */
	public Deliverable deliverable;

	/**
	 * 
	 * @param student_id 
	 * @return 
	 */
	public void viewGrades(int student_id) {
	}

	/**
	 * 
	 * @param student_id 
	 * @param grade_type 
	 * @return 
	 */
	public boolean updateGrades(int student_id, String grade_type) {
		return true;
	}
};
