// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package controllerLogic;

/************************************************************/
/**
 * class Login {
  * 
  * 	public netname: String;
  * 	public password: String;
  * 	public type: Integer;
  * 	public login(in netname: String, in password: String);
  * 	public endSession();
  * 
  * }
 */
public class Login1 {
	/**
	 * 
	 */
	public String netname;
	/**
	 * 
	 */
	public String password;
	/**
	 * 
	 */
	public int type;

	/**
	 * 
	 * @param netname 
	 * @param password 
	 * @return 
	 */
	public boolean login(String netname, String password) {
		return true;
	}

	/**
	 * 
	 */
	public void endSession() {
	}
};
