// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package controllerLogic;

/************************************************************/
/**
 * class Quiz {
  * 
  * 	public assoc 'A_attempts_attempted by' {
  * 		public attempts: Quiz[0..*];
  * 		public 'attempted by': Student[1..*];
  * 	}
  * 
  * 	private q_id: Integer;
  * 	public q_name: String;
  * 	public start();
  * 	public submit();
  * 
  * }
 */
public class Quiz {
	/**
	 * 
	 */
	private int q_id;
	/**
	 * 
	 */
	public String q_name;

	/**
	 * 
	 */
	public void start() {
	}

	/**
	 * 
	 */
	public void submit() {
	}
};
