// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package controllerLogic;

/************************************************************/
/**
 * class Recording {
  * 
  * 	private recording_id: Integer;
  * 	public recording_name: String;
  * 	public startRecording();
  * 	public stopRecording();
  * 	public pauseRecording();
  * 	public saveRecording();
  * 	public deleteRecording();
  * 	public shareRecording();
  * 	public uploadRecording();
  * 	public getRecording_id(): Integer;
  * 	public setRecording_id(in recording_id: Integer);
  * 
  * }
 */
public class Recording {
	/**
	 * 
	 */
	private int recording_id;
	/**
	 * 
	 */
	public String recording_name;

	/**
	 * 
	 */
	public void startRecording() {
	}

	/**
	 * 
	 */
	public void stopRecording() {
	}

	/**
	 * 
	 */
	public void pauseRecording() {
	}

	/**
	 * 
	 */
	public void saveRecording() {
	}

	/**
	 * 
	 */
	public void deleteRecording() {
	}

	/**
	 * 
	 */
	public void shareRecording() {
	}

	/**
	 * 
	 */
	public void uploadRecording() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getRecording_id() {
		return recording_id;
	}

	/**
	 * 
	 * @param recording_id 
	 */
	public void setRecording_id(int recording_id) {
	}
};
