// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package controllerLogic;

import controllerLogic.Course;

/************************************************************/
/**
 * class Stream {
  * 
  * 	private stream_id: Integer;
  * 	public stream_name: String;
  * 	public course: Course[0..1];
  * 	public selectStream(in stream_id: Integer);
  * 	public getStream_id(): Integer;
  * 	public setStream_id(in straem_id: Integer);
  * 
  * }
 */
public class Stream {
	/**
	 * 
	 */
	private int stream_id;
	/**
	 * 
	 */
	public String stream_name;
	/**
	 * 
	 */
	public Course[] course;

	/**
	 * 
	 * @param stream_id 
	 */
	public void selectStream(int stream_id) {
	}

	/**
	 * 
	 * @return 
	 */
	public int getStream_id() {
		return stream_id;
	}

	/**
	 * 
	 * @param straem_id 
	 */
	public void setStream_id(int straem_id) {
	}
};
