// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package controllerLogic;

/************************************************************/
/**
 * class StudyResource {
  * 
  * 	private course_id: Integer;
  * 	private sr_id: Integer;
  * 	public sr_name: String;
  * 	public uploadResource();
  * 	public deleteResource();
  * 
  * }
 */
public class StudyResource {
	/**
	 * 
	 */
	private int course_id;
	/**
	 * 
	 */
	private int sr_id;
	/**
	 * 
	 */
	public String sr_name;

	/**
	 * 
	 */
	public void uploadResource() {
	}

	/**
	 * 
	 */
	public void deleteResource() {
	}
};
