// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package controllerLogic;

/************************************************************/
/**
 * class User {
  * 
  * 	public name: String;
  * 	public email: String;
  * 	public contact: String;
  * 	public address: String;
  * 	public password: String;
  * 	public registration(in name: String, in email: String, in contact: String,
  * 		in address: String, in password: String): Boolean;
  * 
  * }
 */
public class User {
	/**
	 * 
	 */
	public String name;
	/**
	 * 
	 */
	public String email;
	/**
	 * 
	 */
	public String contact;
	/**
	 * 
	 */
	public String address;
	/**
	 * 
	 */
	public String password;

	/**
	 * 
	 * @param name 
	 * @param email 
	 * @param contact 
	 * @param address 
	 * @param password 
	 * @return 
	 */
	public boolean registration(String name, String email, String contact, String address, String password) {
		return true;
	}
};
